export const ACTIVITY_ACTION = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  PASSWORD_RESET: "PASSWORD_RESET",

  CREATE_BLOG: "CREATE_BLOG",
  UPDATE_BLOG: "UPDATE_BLOG",
  DELETE_BLOG: "DELETE_BLOG",
  PUBLISH_BLOG: "PUBLISH_BLOG",

  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  CREATE_TAG: "CREATE_TAG",
  UPDATE_TAG: "UPDATE_TAG",
  DELETE_TAG: "DELETE_TAG",

  CREATE_COMMENT: "CREATE_COMMENT",
  APPROVE_COMMENT: "APPROVE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",

  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  DELETE_IMAGE: "DELETE_IMAGE",

  UPDATE_SETTINGS: "UPDATE_SETTINGS",
};

export default ACTIVITY_ACTION;